url: https://bcfier.com
baseurl: 

# Site settings
title: BCFier
email: hello@teocomi.com
description: "BCFier is an Open Source tool developed to help you create better buildings."

latest: "Latest stableversion is BCFier 2.0.0.0 and it was released on the 5th of July 2015."

about: "BCFier is an Open Source tool developed to help you deliver better buildings."
about1: "Like IFC is the open standard for Building Information models, [BCF](http://www.buildingsmart-tech.org/specifications/bcf-releases) (also developed by buildingSMART) is the open standard for Building Issues. BCFier is a set of plugins and standalone apps that handle BCF and integrate directly with BIM tools."
about2: "Contribute to the Open BIM community by developing and extending BCFier to support more platforms and and online services, BCFier is now Open Source!"

features: "BCFier is an evolving project, stay tuned for updates and new features."

credits: "BCFier is powered by a community of people who love what they do, spend a moment to say thanks."
credits1: "BCFier is an effort stared by Matteo Cominetti [@teocomi](https://twitter.com/teocomi). At the moment there are no other contributors, be the first!"
credits2: "This webpage was created using [Jekyll](http://jekyllrb.com/) and the [Agency theme](http://ironsummitmedia.github.io/startbootstrap-agency/), it's hosted on [GitHub Pages](https://pages.github.com/)."

download: "Download the installer for Windows or fork it on GitHub."

download1: "<p class='lead' markdown='1'>The installer contains all the available modules and you'll be able to select what to install.<br/><br/>If it's the first time you use BCFier, check out the [User Guide](/userguide),<br/>if you are a developer check out the [Documentation](https://github.com/teocomi/BCFier).</p>"

navigation:
- text: About
  url: "/#about"
- text: Features
  url: "/#features"
- text: Download
  url: "/#download"
- text: Credits
  url: "/#credits"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4DBFF5
  secondary: 34A6DC  
  secondary-dark: 14324A

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/BCFier
  - title: github
    url: https://github.com/teocomi/BCFier

# Build settings
markdown: kramdown
permalink: pretty